# Generated by Django 5.2.5 on 2025-09-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='1 month', max_length=20),
        ),
    ]
