# Generated by Django 5.2.5 on 2025-09-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscriptionplan_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('1 month', 'Monthly'), ('1 year', 'Yearly')], default='1 month', max_length=20),
        ),
    ]
