# Generated by Django 5.2.5 on 2025-09-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_helpcentercategory_issuetype_faq_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
        migrations.DeleteModel(
            name='HelpCenterCategory',
        ),
    ]
