# Generated by Django 5.2.5 on 2025-09-20 10:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_faq_category_delete_helpcentercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportissue',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
