# Generated by Django 5.2.4 on 2025-08-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='allows_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='has_offers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='price_range',
            field=models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$')], default=1),
        ),
    ]
