# Generated by Django 5.2.4 on 2025-08-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_shop_allows_pickup_shop_has_offers_shop_price_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='price_range',
            field=models.IntegerField(choices=[(1, 'start'), (2, 'medium'), (3, 'high')], default=1),
        ),
    ]
