# Generated by Django 5.2.4 on 2025-08-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_shop_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
