# Generated by Django 5.2.4 on 2025-08-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_shop_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='opens_at',
            field=models.TimeField(blank=True, help_text='যদি বন্ধ থাকে, তাহলে খোলার সময়', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='delivery_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='ডেলিভারির জন্য আনুমানিক সময় (মিনিটে)', null=True),
        ),
    ]
