# Generated by Django 5.2.4 on 2025-08-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_shop_is_open_shop_opens_at_shop_shop_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='opens_at',
        ),
        migrations.AlterField(
            model_name='shop',
            name='delivery_time_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='এই দিনে কি শপটি পুরোপুরি বন্ধ থাকবে?')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='homepage.shop')),
            ],
            options={
                'unique_together': {('shop', 'day')},
            },
        ),
    ]
