# Generated by Django 5.2.4 on 2025-08-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_shop_is_open_remove_shop_opens_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='allows_delivery',
            field=models.BooleanField(default=True, help_text='support delivery or not'),
        ),
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_address',
            field=models.CharField(blank=True, help_text='give address', max_length=255, null=True),
        ),
    ]
