# Generated by Django 5.2.5 on 2025-08-19 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_shop_allows_delivery_shop_latitude_shop_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='deal_validity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='min_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='offers',
            field=models.CharField(default='write offer', max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='redemption_type',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup'), ('Delivery & Pickup', 'Delivery & Pickup')], default='delivery & pickup', max_length=30),
        ),
    ]
