# Generated by Django 5.2.5 on 2025-08-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_shop_deal_validity_shop_is_favourite_shop_min_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='allows_pickup',
        ),
    ]
