# Generated by Django 5.2.5 on 2025-09-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_businesshours_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Is this closed Shop full day '),
        ),
    ]
