# Generated by Django 5.2.5 on 2025-09-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_shop_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='shop',
        ),
    ]
