# Generated by Django 5.2.5 on 2025-09-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_businesshours_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshours',
            name='user',
        ),
    ]
