# Generated by Django 5.2.5 on 2025-09-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_remove_businesshours_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessHours',
        ),
    ]
