# Generated by Django 5.2.5 on 2025-09-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Business_profile_Category',
        ),
    ]
