# Generated by Django 5.2.5 on 2025-09-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_deliverycost_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_deal',
            name='business_profile',
        ),
    ]
