# Generated by Django 5.2.5 on 2025-09-02 04:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_modifiergroup_vendor_category_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='image',
            field=cloudinary.models.CloudinaryField(default='logo.jpg', max_length=255, verbose_name='logo'),
        ),
    ]
