# Generated by Django 5.2.5 on 2025-09-03 05:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_create_deal_business_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor_category',
            options={},
        ),
        migrations.RemoveField(
            model_name='vendor_category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendor_category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vendor_category',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vendor_category',
            name='category_description',
            field=models.TextField(default='write description'),
        ),
        migrations.AddField(
            model_name='vendor_category',
            name='category_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='vendor_category',
            name='category_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vendor_category',
            name='category_title',
            field=models.CharField(default='write title', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor_category',
            name='choice_category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks')], max_length=50, null=True),
        ),
    ]
