# Generated by Django 5.2.5 on 2025-09-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_deal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='modifier_groups',
            field=models.ManyToManyField(related_name='deals', to='vendors.modifiergroup'),
        ),
    ]
