# Generated by Django 5.2.5 on 2025-09-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_create_deal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_deal',
            name='discount_type',
        ),
    ]
