# Generated by Django 5.2.5 on 2025-09-17 10:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_profile_category',
            name='category_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='logo'),
        ),
    ]
