# Generated by Django 5.2.5 on 2025-09-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_business_profile_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_deal',
            name='cooking_time',
            field=models.CharField(blank=True, help_text='Estimated cooking time in minute for the deal', max_length=100, null=True),
        ),
    ]
