# Generated by Django 5.2.5 on 2025-09-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_create_deal_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_deal',
            name='cooking_time',
        ),
    ]
