# Generated by Django 5.2.5 on 2025-09-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_remove_create_deal_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_deal',
            name='redemption_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Pickup')], max_length=20),
        ),
    ]
