# Generated by Django 5.2.5 on 2025-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_alter_create_deal_redemption_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_deal',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='deals_qr/'),
        ),
    ]
