# Generated by Django 5.2.5 on 2025-09-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_create_deal_qr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_deal',
            old_name='qr',
            new_name='qrimage',
        ),
    ]
