# Generated by Django 5.2.5 on 2025-09-28 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_wishdeal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create_deal',
            options={'verbose_name': "Vendor's Deal", 'verbose_name_plural': "Vendor's Deals"},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterField(
            model_name='create_deal',
            name='discount_value',
            field=models.CharField(choices=[('0', '0'), ('5', '5'), ('10', '10'), ('25', '25'), ('50', '50'), ('1+1', '1+1'), ('FREE ITEM', 'FREE ITEM'), ('PRE ORDER', 'PRE ORDER'), ('LATE NIGHT', 'LATE NIGHT'), ('QOUPON+', 'QOUPON+')], max_length=30),
        ),
        migrations.CreateModel(
            name='DealTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.create_deal')),
            ],
        ),
    ]
