# Generated by Django 5.2.5 on 2025-09-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_alter_create_deal_options_alter_deal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_deal',
            name='discount_value',
        ),
        migrations.AddField(
            model_name='create_deal',
            name='deal_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Both', 'Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='create_deal',
            name='discount_value_free',
            field=models.CharField(blank=True, choices=[('0', '0'), ('5', '5'), ('10', '10'), ('25', '25'), ('50', '50'), ('1+1', '1+1'), ('FREE ITEM', 'FREE ITEM'), ('PRE ORDER', 'PRE ORDER'), ('LATE NIGHT', 'LATE NIGHT'), ('QOUPON+', 'QOUPON+')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='create_deal',
            name='discount_value_paid',
            field=models.CharField(blank=True, choices=[('0', '0'), ('5', '5'), ('10', '10'), ('25', '25'), ('50', '50'), ('1+1', '1+1'), ('FREE ITEM', 'FREE ITEM'), ('PRE ORDER', 'PRE ORDER'), ('LATE NIGHT', 'LATE NIGHT'), ('QOUPON+', 'QOUPON+')], max_length=30, null=True),
        ),
    ]
