# Generated by Django 5.2.5 on 2025-10-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_business_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_deal',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
