# Generated by Django 5.2.5 on 2025-10-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_create_deal_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_deal',
            name='activation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='create_deal',
            name='redemption',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
