# Generated by Django 5.2.5 on 2025-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_create_deal_activation_create_deal_redemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiergroup',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
