# Generated by Django 5.2.5 on 2025-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_ingredient_ingredientsoption_deal_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
