# Generated by Django 5.2.5 on 2025-10-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_alter_ingredientsoption_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='options',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='modifiergroup',
            name='price',
        ),
        migrations.DeleteModel(
            name='IngredientsOption',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
