# Generated by Django 5.2.5 on 2025-10-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0025_remove_ingredient_options_remove_deal_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiergroup',
            name='modifiers',
            field=models.JSONField(blank=True, default=list, help_text="Format: [{'id': 'id', 'name': 'name', 'price': 'price'}]"),
        ),
    ]
