# Generated by Django 5.2.5 on 2025-10-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0026_modifiergroup_modifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='modifiergroup',
            name='modifiers',
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='modifiers',
            field=models.ManyToManyField(related_name='modifier_groups', to='vendors.modifier'),
        ),
    ]
