# Generated by Django 5.2.5 on 2025-10-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0027_modifier_modifiergroup_is_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='modifier_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='deals', to='vendors.modifiergroup'),
        ),
    ]
