# Generated by Django 5.2.5 on 2025-10-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0028_alter_deal_modifier_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='modifier_groups',
        ),
        migrations.AddField(
            model_name='deal',
            name='modifiers',
            field=models.JSONField(blank=True, default=list, help_text='Format: [\n            {\n                "name": "Select Your Bread",\n                "is_required": true,\n                "options": [\n                    {"title": "Classic Bread", "Price": 2.50},\n                    {"title": "Brown Bread", "Price": null}\n                ]\n            }\n        ]'),
        ),
    ]
