# Generated by Django 5.2.5 on 2025-10-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0029_remove_deal_modifier_groups_deal_modifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_deal',
            name='push_sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
