# Generated by Django 5.2.5 on 2025-10-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0031_businesdeliverycost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='business_profile',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='business_profiles', to='vendors.label'),
        ),
    ]
