# Generated by Django 5.2.5 on 2025-10-20 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0032_label_business_profile_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_profile',
            name='label',
        ),
        migrations.AddField(
            model_name='business_profile',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profiles', to='vendors.label'),
        ),
    ]
