# Generated by Django 5.2.4 on 2025-08-14 04:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review_count', models.CharField(default='500+', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tags', models.CharField(help_text='Comma-separated tags e.g., Vegan, Gezond, Pizza', max_length=255)),
                ('discount_percentage', models.IntegerField(default=0)),
            ],
        ),
    ]
