# Generated by Django 5.2.5 on 2025-08-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_options',
        ),
    ]
