# Generated by Django 5.2.4 on 2025-08-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(related_name='restaurants', to='discover.cuisine'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='diets',
            field=models.ManyToManyField(related_name='restaurants', to='discover.diet'),
        ),
    ]
