# Generated by Django 5.2.5 on 2025-08-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_remove_cartitem_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
    ]
