# Generated by Django 5.2.5 on 2025-09-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_reviewmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reviewmenuitem',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
