# Generated by Django 5.2.4 on 2025-08-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_cuisine_diet_restaurant_cuisines_restaurant_diets'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average price for one person', max_digits=6, null=True),
        ),
    ]
