# Generated by Django 5.2.5 on 2025-08-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_alter_optionchoice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
