# Generated by Django 5.2.5 on 2025-09-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_faq_alter_reviewmenuitem_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
