# Generated by Django 5.2.5 on 2025-08-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_menuitem_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionchoice',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
