# Generated by Django 5.2.4 on 2025-08-14 09:30

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_restaurant_average_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('valid_until', models.DateTimeField()),
                ('discount_percentage', models.IntegerField()),
                ('redemption_methods', models.CharField(help_text='e.g., Delivery & Pickup', max_length=100)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_offers', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='discover.restaurant')),
            ],
        ),
    ]
