# Generated by Django 5.2.5 on 2025-09-21 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_delete_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discover_cart_items', to='discover.menuitem'),
        ),
    ]
