# Generated by Django 5.2.4 on 2025-08-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeSubscriptionOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Pret Coffee Subscription', max_length=100)),
                ('description', models.TextField(default='All your organic coffees (and teas, frappes, hot chocolates...)')),
                ('price_details', models.CharField(default='for £20 a month', max_length=100)),
                ('offer_details', models.CharField(default='and your first month FREE', max_length=100)),
                ('website_url', models.URLField(default='http://PretCoffeeSub.co.uk')),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
