# Generated by Django 5.2.5 on 2025-08-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_optionchoice_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_options',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='optiongroup',
            name='item',
        ),
        migrations.RemoveField(
            model_name='optionchoice',
            name='group',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='OptionChoice',
        ),
        migrations.DeleteModel(
            name='OptionGroup',
        ),
    ]
