# Generated by Django 5.2.5 on 2025-08-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0005_coffeesubscriptionoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(default='500+', max_length=20),
        ),
    ]
