# Generated by Django 5.2.5 on 2025-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0006_optionchoice_cart_menucategory_menuitem_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_type',
            field=models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], default='DELIVERY', max_length=10),
        ),
    ]
