# Generated by Django 5.2.5 on 2025-10-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0006_reviewreply'),
        ('vendors', '0029_remove_deal_modifier_groups_deal_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendors.deal'),
        ),
    ]
