# Generated by Django 5.2.5 on 2025-08-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0007_alter_restaurant_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(),
        ),
    ]
