# Generated by Django 5.2.5 on 2025-08-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0007_cart_delivery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='is_selected',
            new_name='added_to_cart',
        ),
    ]
