# Generated by Django 5.2.5 on 2025-08-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0009_alter_menucategory_name_alter_menuitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionchoice',
            name='title',
            field=models.CharField(default='write title', max_length=200),
        ),
    ]
