# Generated by Django 5.2.5 on 2025-08-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0010_optionchoice_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionchoice',
            old_name='title',
            new_name='selected_title',
        ),
    ]
