# Generated by Django 5.2.5 on 2025-08-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0010_vendorfollowed_deal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
