# Generated by Django 5.2.5 on 2025-08-18 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0011_delete_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorfollowed',
            old_name='name',
            new_name='descriptions',
        ),
        migrations.AddField(
            model_name='vendorfollowed',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendorfollowed',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=200, null=True),
        ),
    ]
