# Generated by Django 5.2.4 on 2025-08-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
