# Generated by Django 5.2.4 on 2025-08-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(help_text='must be unique', unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Bengali', 'Bengali'), ('Spanish', 'Spanish')], default='en', max_length=10),
        ),
    ]
