# Generated by Django 5.2.5 on 2025-09-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_profile_address_profile_city_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mollie_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
