# Generated by Django 5.2.5 on 2025-09-25 03:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_fcmdevice_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together={('user', 'registration_id')},
        ),
    ]
