# Generated by Django 5.2.5 on 2025-09-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_fcmdevice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together=set(),
        ),
    ]
