# Generated by Django 5.2.5 on 2025-09-21 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discover', '0005_menuitem_item_availability_alter_cartitem_menu_item'),
        ('vendors', '0013_alter_create_deal_redemption_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_deal', to='order.cart')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.create_deal')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('special_instructions', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='order.cart')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart_items', to='discover.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cart_snapshot', models.JSONField(blank=True, help_text='Snapshot of cart data at time of order', null=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('RECEIVED', 'Order Received'), ('PREPARING', 'In Preparation'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('READY_FOR_PICKUP', 'Ready for Pick Up'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('delivery_type', models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('order_type', models.CharField(choices=[('STANDARD', 'Standard Order'), ('SCHEDULED', 'Scheduled Order')], default='STANDARD', max_length=10)),
                ('scheduled_datetime', models.DateTimeField(blank=True, help_text='Required if order_type is SCHEDULED. When the order should be delivered/ready for pickup.', null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_code', models.CharField(blank=True, help_text='Unique code for delivery QR verification', max_length=12, null=True, unique=True)),
                ('delivery_code_created_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_code_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal_title', models.CharField(max_length=255)),
                ('deal_description', models.TextField()),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.create_deal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_deals', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discover.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('RECEIVED', 'Order Received'), ('PREPARING', 'In Preparation'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('READY_FOR_PICKUP', 'Ready for Pick Up'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='order.order')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
