# Generated by Django 5.2.5 on 2025-09-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_code',
            field=models.CharField(blank=True, help_text='Unique code for delivery QR verification', max_length=6, null=True, unique=True),
        ),
    ]
