# Generated by Django 5.2.5 on 2025-09-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_delivery_code'),
        ('vendors', '0015_rename_qr_create_deal_qrimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='deal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_cart_items', to='vendors.deal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.deal'),
        ),
    ]
