# Generated by Django 5.2.5 on 2025-09-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_cartitem_menu_item_remove_orderitem_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
