# Generated by Django 5.2.5 on 2025-09-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_delivery_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
