# Generated by Django 5.2.5 on 2025-09-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrCodeApp', '0002_qrcode_delete_userqr'),
        ('order', '0005_remove_cartitem_special_instructions_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='QrCodeApp.qrcode'),
        ),
    ]
