# Generated by Django 5.2.5 on 2025-09-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='special_instructions',
            new_name='note',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='order_items/'),
        ),
    ]
