# Generated by Django 5.2.5 on 2025-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_payment_id_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
