# Generated by Django 5.2.5 on 2025-10-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_estimated_delivery_time'),
        ('vendors', '0024_alter_ingredientsoption_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_ingredients',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'ingredient_id': ['option_id1', 'option_id2']}"),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_modifiers',
            field=models.ManyToManyField(blank=True, to='vendors.modifiergroup'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ingredients_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modifiers_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_ingredients',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'ingredient_id': {'name': 'name', 'options': [{'id': 'id', 'name': 'name', 'price': 'price'}]}}"),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_modifiers',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'modifier_id': {'name': 'name', 'price': 'price'}}"),
        ),
    ]
