# Generated by Django 5.2.5 on 2025-10-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_cartitem_selected_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_ingredients',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ingredients_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_ingredients',
        ),
    ]
