# Generated by Django 5.2.5 on 2025-10-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_cartitem_selected_ingredients_and_more'),
        ('vendors', '0027_modifier_modifiergroup_is_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_modifier_groups',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='vendors.modifiergroup'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selected_modifiers',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='vendors.modifier'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_modifiers',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'modifier_group_id': {'name': 'group_name', 'required': bool, 'selections': [{'id': id, 'name': 'name', 'price': price}]}}"),
        ),
    ]
