# Generated by Django 5.2.5 on 2025-10-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_cartitem_selected_modifier_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_modifier_groups',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_modifiers',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_modifiers',
            field=models.JSONField(blank=True, default=list, help_text='Format: [\n            {\n                "group_name": "Select Your Bread",\n                "selected_options": ["Classic Bread"]\n            }\n        ]'),
        ),
    ]
