# Generated by Django 5.2.5 on 2025-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_cartitem_selected_modifier_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('MOLLIE', 'Mollie'), ('CASH', 'Cash on Delivery/Pickup')], default='MOLLIE', max_length=50, null=True),
        ),
    ]
