# Generated by Django 5.2.5 on 2025-10-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
